
project_id = "wacicyiidaysfjdiaeim"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[functions]
[functions.bitcoin-service]
verify_jwt = true

[functions.price-engine]
verify_jwt = true
