// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wacicyiidaysfjdiaeim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhY2ljeWlpZGF5c2ZqZGlhZWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTA5NDUsImV4cCI6MjA2MzA2Njk0NX0.6FpJppdFQNPkmd6dBxsShPbLtLYe0LAS2YrsN84LTUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);